crates/rari-doc/src/html/rewriter.rs
Adds `<figure class="table-container">` around `<math display="block">` to contain oversized formulas, just like it does for oversized tables.
Before
https://github.com/user-attachments/assets/29c63df5-102d-4115-a142-7e9cb1e5aea1
After
https://github.com/user-attachments/assets/164bb081-8a58-4545-a854-aa94b5cc4a2e
In the next step, it would make sense to rename it to `overflow-container` since it’s not exclusive to tables anymore.
=> Add a scrolling container around block math elements

crates/rari-doc/src/pages/types/spa_homepage.rs
The repo name of translated content is `mdn/translated-content`, not `mdn/translated_content`.
Check the "Recent contributions" section in the [Home page](https://developer.mozilla.org/). The 
URLs to translated-content's PRs are broken. It's also reported in the MDN official Discord channel.
=> fix(l10n): correct the repo name to translated content

crates/rari-doc/src/sidebars/jsref.rs
As a part of https://github.com/mdn/content/pull/37344/, we need to support displaying `Temporal` in a similar fashion as `Intl`. To do so I made several refactors to avoid repeating myself.
As an aside I'm amused by how much we use `Cow` when most of the strings here are immutable anyway.
=> feat(sidebars/jsref): support temporal

crates/rari-md/src/node_card.rs
correct the prefix string for notecards in zh-TW locale.
The prefix string for ntoecards in zh-TW locale appears to be identical to the zh-CN locale. Fix them by copying those prefix strings from [yari](https://github.com/mdn/yari/blob/0b5276be8dc2b10992f1fe91ebdc8f7c0285430e/markdown/localizations/zh-TW.json)
A screenshot from https://developer.mozilla.org/zh-TW/docs/Web/CSS/@font-face#%E6%8F%8F%E8%BF%B0:
/cc @mdn/yari-content-zh
=> fix(l10n): correct the prefix string for notecards in zh-TW locale

crates/rari-doc/src/templ/parser.rs, crates/rari-doc/src/templ/rari-templ.pest, crates/rari-doc/src/templ/templs/embeds/embed_gh_live_sample.rs, crates/rari-doc/src/templ/templs/embeds/embed_live_sample.rs, crates/rari-doc/src/templ/templs/embeds/jsfiddle_embed.rs, crates/rari-doc/src/templ/templs/links/domxref.rs, crates/rari-doc/src/templ/templs/links/rfc.rs, crates/rari-types/src/lib.rs
replace empty string args for macos with `None`s
In mdn/content, we are used to use empty string to represent the argument is not provided, which should be `None` instead of `Some(EmptyString)`. But we have use some judgement like `if let Some(anchor) = anchor` to check if the string argument is provided. This will evaluate to `true` as the judgement encounters a string.
I found an incorrect case in `/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction/onClicked` page:
There is a hash symbol at the end of the link text.
I think the easiest solution is to replace the empty string args with `None`s. As we use similar logic to the above to determine whether the parameters are provided in many macos. Some cases (Maybe not all of them):
- crates/rari-doc/src/templ/templs/links/domxref.rs …
=> fix(build/parser): parse empty string args for macros as `None`s

crates/rari-doc/src/html/rewriter.rs
trim the first empty line in `<pre>` tag
The adding of `<code>` tag makes the first empty line would not be ignored by User Agent, see the [spec](https://www.w3.org/MarkUp/1995-archive/Elements/PRE.html). Ref: https://github.com/mdn/yari/issues/12364#issuecomment-2561133409
So trimming the first empty line in `<pre>` tag to simulate the semantics.
Fixes: mdn/yari#12364
Test: check the rendered html in `/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action`:
Before:
After:
=> fix(html): trim the first empty line in `<pre>` tag

crates/rari-cli/main.rs
Previously, we often encountered installation issues with vscode-ripgrep when installing the Node.js environment in GitHub workflow (caused by the rate limit of anonymous GitHub API calls). So we uses GitHub Token to avoid this problem: https://github.com/mdn/content/blob/452d2ecc73ecde2253bbfdfbb10f45cf6022257d/.github/workflows/pr-test.yml#L60-L62
I think we may also face this problem if we try to [update rari in workflows](https://github.com/mdn/content/blob/452d2ecc73ecde2253bbfdfbb10f45cf6022257d/.github/workflows/pr-test.yml#L104). The best solution is to try to use GitHub Token to call the update API during self-updating in workflows.
I've tested the function with [Fine-grained PAT](https://github.blog/security/application-security/introducing-fine-grained-personal-access-tokens-for …
=> chore(ci): set the auth token for the update API when provided through the env variable

crates/rari-doc/src/templ/templs/embeds/interactive_example.rs
Small fix to https://github.com/mdn/rari/pull/84
Was rendering as `height=taller"`
=> fix(interactive-example): missing quote at start of height attribute

.github/workflows/build-and-upload-binaries.yml, .github/workflows/lint-test-clippy.yaml, .github/workflows/release-please-pr.yml, .github/workflows/release-please-release.yml
Pin 3rd party actions to a commit hash to mitigate the risk of a supply chain attack.
Resolves [5 CodeQL code scanning alerts](https://github.com/mdn/rari/security/code-scanning?query=is%3Aopen+branch%3Amain+rule%3Aactions%2Funpinned-tag).
Related:
- https://github.com/mdn/browser-compat-data/pull/25793
- https://github.com/mdn/content/pull/38016
- https://github.com/mdn/rumba/pull/602
- https://github.com/mdn/translated-content/pull/25752
- https://github.com/mdn/translated-content-de/pull/53
- https://github.com/mdn/workflows/pull/155
=> ci(workflows): pin 3rd party actions

rari-npm/lib/download.js
`@mdn/rari` cannot be installed with Node.js v22.12+, as it using `require()` in .js files with `"type": "module"` in `package.json`, which is currently incompatible with Node.js v22.12.0 due to stricter module handling. See: nodejs/node#56155.
Use `import` to dynamically load esm modules, as we have already use this in the current file: https://github.com/mdn/rari/blob/03270403a060318163d8afff35c8a1275b2e6e56/rari-npm/lib/download.js#L68
I cannot successfully run `yarn install` in `mdn/content` with Node.js v22.13 installed.
I've run `npm install && npm run export-schema && npm run generate-types && npm pack` in `rari-npm`.
And replace the `@mdn/rari` package in mdn/content locally, which makes the installation with Node.js v22.13 successful.
=> fix(npm): use `import` to dynamically load esm modules

crates/rari-doc/src/helpers/css_info.rs
Update URLs in the CSSInfo macro
Seeing flaws in the content PRs.
https://github.com/mdn/content/pull/38202#issuecomment-2664453665
=> fix(macro): update redirects in CSSInfo

.github/ISSUE_TEMPLATE/bug.yml
The link to `CONTRIBUTING.md` is broken, GitHub may use the `path/to/repo` as the base URL for the issue template. This PR corrected the relative path.
I've tested in my repo (switching the default branch to this one `broken-contributing-link`):
The issue which has mentioned the problem: #140
=> fix(issue-template): make `CONTRIBUTING.md` link absolute

crates/rari-doc/src/templ/templs/links/csp.rs, crates/rari-doc/src/templ/templs/links/http.rs, crates/rari-tools/src/sidebars.rs
We've recently moved some docs in the HTTP section. This updates some paths so we don't have unnecessary redirects.
__related issues and PRs:__
=> fix: update paths for HTTP section move

crates/rari-cli/main.rs, crates/rari-cli/serve.rs, crates/rari-doc/src/issues.rs, crates/rari-doc/src/pages/page.rs, crates/rari-doc/src/pages/types/blog.rs, crates/rari-doc/src/pages/types/contributors.rs, crates/rari-doc/src/pages/types/curriculum.rs, crates/rari-doc/src/pages/types/doc.rs, crates/rari-doc/src/pages/types/generic.rs, crates/rari-doc/src/pages/types/spa.rs, crates/rari-tools/src/fix/fixer.rs, crates/rari-tools/src/fix/issues.rs, crates/rari-tools/src/fix/mod.rs, crates/rari-tools/src/lib.rs
Adds cli support for `content fix-flaws`.
By default it fixed all (broken_links) issues for all available locales.
Support `-l <LOCALE>` to restrict it to a single locale.
Experimental support for the API used by the flaws box in the front-end (depending on a yari PR).
=> feat(content): support fix-flaws command

crates/rari-doc/src/templ/templs/links/mathmlxref.rs, crates/rari-doc/src/templ/templs/links/svgattr.rs, crates/rari-doc/src/templ/templs/links/svgxref.rs
We've recently moved some docs in MathML and SVG sections.
This updates some paths so we don't have unnecessary redirects.
Depends one these PRs:
=> fix: update paths for SVG/MathML section move

crates/rari-types/src/error.rs
Correct the environment name of `content_translated_root`.
When working with translated-content, the environment name `CONTENT_TRANSLATED_ROOT` should be set, instead of `TRANSLATED_CONTENT_ROOT`. I believe the error message here is a typo.
See the following code/doc for more information:
- https://github.com/mdn/rari/blob/72ee2423fc0ee6e48032a3eb06eee0b26c702acf/crates/rari-types/src/settings.rs#L59
- https://github.com/mdn/rari/blob/72ee2423fc0ee6e48032a3eb06eee0b26c702acf/crates/rari-types/src/settings.rs#L105-L108
- https://github.com/mdn/yari/blob/ad04254426fe69b5c619918bd83a5d845bba9f4a/libs/env/index.js#L83-L85
- https://github.com/mdn/translated-content/blob/main/CONTRIBUTING.md#link-translated-content
=> chore: correct the environment name of `content_translated_root`

crates/rari-doc/src/sidebars/apiref.rs
Currently, the extension methods are not available in the sidebar:
By treating `webgl-extension-method` the same as `web-api-instance-method`, this page can now be included in the sidebar.
=> feat(sidebars): allow webgl-extension-method to show up in ApiRef sidebar

crates/rari-doc/src/helpers/css_info.rs
The hardcoded URLs in the macro are being redirected to the new locations.
Fix flaws.
- addresses https://github.com/mdn/content/pull/39451#issuecomment-2861950429
=> fix(macro): update redirected URLs in the CSSInfo macro

crates/rari-types/src/fm_types.rs
Allowing a `firefox-release-notes-active` page type variant.
Renaming the page type will require an update in content after this PR has landed.
We're using some filtering logic in content to show pages in current active Firefox release cycle.
Fixes #221
=> chore(page-types): add `firefox-release-notes-active` page type

crates/rari-deps/src/client.rs, crates/rari-deps/src/error.rs
Add GitHub token support for API requests, this is a part of fix to resolve the problem described on discord (Got `Error: invalid type: map, expected a sequence` when running [yarn build in GitHub workflows](https://github.com/mdn/content/blob/main/.github/workflows/pr-test.yml#L109)):
I finally figure out what is going on: The error was not caused by "updating xyz To va.b.c", but by rari encountering a rate limiting problem when trying to [get the release info list on GitHub using GitHub API](https://github.com/mdn/rari/blob/82b80b07c462d047648c2c36a242caa8163d5ba5/crates/rari-deps/src/github_release.rs#L21-L26).
To verify this, you can remove the cached version check info, set the wrong **GITHUB_TOKEN** in the environment variable, and you will get output similar to the following:
> …
=> feat(client): add GitHub token support for API requests

crates/rari-doc/src/pages/build.rs, crates/rari-doc/src/pages/json.rs, crates/rari-doc/src/pages/types/generic.rs
Allows setting `short-title` for generic pages (to control the breadcrumb entry).
We sometimes want a different title in the breadcrumbs than in the `<title>`, e.g. "MDN Community" for the community page.
Part of https://github.com/mdn/rari/issues/273.
=> enhance(pages): support short-title for generic

crates/rari-doc/src/pages/build.rs, crates/rari-doc/src/pages/json.rs, crates/rari-doc/src/pages/page.rs, crates/rari-doc/src/pages/types/spa.rs, crates/rari-doc/src/translations.rs
Adds `other_translations` to non-`Doc` pages (Curriculum, SPA incl. Blog Index, Blog posts, Generic content).
Consistency: The language selector is currently only shown on doc pages.
Downstream:
- https://github.com/mdn/fred/pull/345
=> enhance(page): add other_translations to non-Doc pages

.github/workflows/lint-test-clippy.yaml, crates/rari-data/src/baseline.rs, crates/rari-doc/src/html/sections.rs, crates/rari-lsp/src/lsp.rs
Update toolchain to get the latest clippy updates
Linter was failing in ci, but not locally.
See this [CI run](https://github.com/mdn/rari/actions/runs/16880147078/job/47813767251)
=> chore(clippy): update rust toolchain, added elided lifetime specifiers
